yashim-deriv/websockets-dev

_includes/header.html

Fixed navbar active links.

---

_pages/index.html

Fixed links

---

_pages/docs/code-samples.html
_pages/docs/index.html

Content Fix

---

_layouts/documentation.html
_layouts/playground.html
css/main.scss

Fix layout for documentation and playground templates

---

css/main.scss

Hotfix fix mobile views for layout change

---

_includes/token-input.html
_layouts/default.html
_pages/index.html
css/main.scss

Further layout fixes

---

css/main.scss

Fixed homepage desktop and mobile views

---

_includes/offcanvas-menu.html
css/main.scss
deriv.js

Add dropdown nav for off canvas menu. Refactor CSS to use SASS features

---

_includes/head.html
_layouts/default.html
_pages/index.html
css/main.scss

Fixed Lighthouse Score

---

_pages/docs/bug-bounty.html
css/main.scss

Refactored bug bounty page to make use of SASS features

---

_pages/docs/api-guide.html
css/main.scss

Add copy button for light-themed cards

---

css/main.scss
deriv.js

Add copy code functionality

---

_includes/token-input.html
css/main.scss

CSS Fixes + Refactor

---

_includes/header.html
_pages/index.html

Fixed ligthouse score

---

_includes/head.html
css/main.scss

Refactor and add fallback

---

_includes/head.html

Further fix

---

_includes/header.html
_includes/mobile-page-selector.html
_includes/offcanvas-menu.html
_includes/sidebar.html

Fixed default playground link

---

css/main.scss

Add mobile breakpoints

---

_includes/footer.html
_pages/docs/api-guide.html
_pages/docs/index.html
_pages/index.html
css/main.scss
deriv.js

Added footer. Fixed design discrepancies

---

css/main.scss
docson/box.html
docson/docson.css
docson/docson.js

Completed API Playground

---

_pages/playground/index.html
css/main.scss

Fixed button layout according to design

---

css/main.scss

Fixed list-style overlapping

---

_pages/playground/index.html
css/main.scss

Add separator. Fixed CTA alignment.

---

_pages/docs/app-registration.html
_pages/playground/index.html
css/main.scss

Fixed label position

---

css/main.scss

Fixed main page responsive design

---

css/main.scss
deriv.js

Added new mobile nav styling

---

css/main.scss

Fixed main page not centering

---

css/main.scss

Fixes to main page responsive layout

---

_includes/header.html
deriv.js

Added a click outside to close off canvas menu

---

css/main.scss

Fixed h1 header font size on mobile

---

_includes/header.html

Fixed deriv logo

---

css/main.scss

Fixed font size in main page

---

_pages/docs/index.html

Fixed broken redirect link in quickstart page

---

_pages/index.html

Fixed link to JS Library in Main Page

---

_pages/docs/index.html

Fixed missing text in quickstart page

---

_pages/docs/faq.html

Fixed incorrect link in FAQ Page

---

css/main.scss

Fixed spacing in app registration page

---

_pages/docs/app-registration.html
css/main.scss

Fix app registration labels

---

Gemfile
_pages/index.html

Add line break. Restored gemfile

---

_pages/index.html
css/main.scss

Fixed margin bottom for icons

---

_pages/index.html
css/main.scss

Fix icon padding bottom

---

_pages/docs/bug-bounty.html

Update bug bounty program + link

---

_pages/docs/bug-bounty.html

Fixed missing bug bounty text

---

Gemfile
_pages/index.html

Updated jekyll + other dependencies

---

_config.yml

Updated config to deriv.com

---

_pages/docs/api-guide.html

Fixed API guide link

---

css/main.scss
docson/docson.css

Minor fix API Playground layout

---

_pages/index.html
css/main.scss

https://redmine.deriv.cloud/issues/24507#[Mobile]_Scope_checkboxes_are_not_as_per_the_design
https://redmine.deriv.cloud/issues/24508#[Mobile-Homepage]_Text_alignment_and_spacing_is_not_as_per_the_design

fourth phase of QA fixes

---

_pages/playground/index.html

Swapped buttons

---

_pages/docs/api-guide.html
css/main.scss

Fixed API Guide Mobile

---

_includes/head.html

Fixed default client zoom

---

_includes/head.html

Readded default Docson CSS

---

_pages/docs/app-registration.html

Fixed 25071 - default check removal

---

_includes/header.html
_includes/mobile-page-selector.html
_includes/offcanvas-menu.html
_includes/sidebar.html
_pages/docs/index.html

Fixed default link to API Playground

---

_pages/docs/faq.html
index.html

Fixed all links that are pointing to binary.com

---

css/main.scss

Layout fixes

---

_pages/docs/api-guide.html

Fixed Token Link

---

css/main.scss

Fixed dropdown colour in firefox

---

_pages/docs/app-registration.html
css/main.scss

Add labels to input group

---

css/main.scss

Made sidebar fixed

---

index.html

Fixed best practice score

---

_includes/head.html

Load render blocking script async

---

_includes/head.html
css/main.scss

Fixed binary api loading

---

css/select2.min.css

Fixed select box

---

_pages/docs/app-registration.html
css/main.scss

Fixed request json container

---

css/main.scss

Fixed font size for label and alignment

---

css/main.scss

Fixed Console

---

_pages/docs/app-registration.html
css/main.scss

Added responsive table

---

css/main.scss

Fixed table colour

---

css/main.scss

Improve user-friendliness of code console

---

_pages/docs/app-registration.html
code.js
css/main.scss

Fixed broken update functionality

---

css/main.scss

CSS Cleanup

---

css/main.scss

Updated hover color

---

css/main.scss

Fixed api playground console size
